version: "3"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: bobba
    ports:
      - "3306:3306"
  fileserver:
    image: halverneus/static-file-server:latest
    ports:
      - "8084:8080"
    environment:
      FOLDER: /content
    volumes:
      - content:/content

volumes:
  content:
    driver: local
    driver_opts:
      type: none
      device: content
      o: bind